# TCL File Generated by Component Editor 11.1sp2
# Sat Aug 17 12:49:15 CEST 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | spi_master "SPI Master (3 Wire Serial)" v1.3
# | Michael Fischer 2013.08.17.12:49:15
# | SPI Master (3 Wire Serial)
# | 
# | ip/spi_master/spi_master_if.vhd
# | 
# |    ./spi_master_if.vhd syn, sim
# |    ./spi_master_core.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module spi_master
# | 
set_module_property DESCRIPTION "SPI Master (3 Wire Serial)"
set_module_property NAME spi_master
set_module_property VERSION 1.3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Michael Fischer"
set_module_property DISPLAY_NAME "SPI Master (3 Wire Serial)"
set_module_property TOP_LEVEL_HDL_FILE spi_master_if.vhd
set_module_property TOP_LEVEL_HDL_MODULE spi_master_if
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME spi_master_if
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file spi_master_if.vhd {SYNTHESIS SIMULATION}
add_file spi_master_core.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | documentation links
# | 
add_documentation_link "Data Sheet" "http://www.emb4fun.de/fpga/components/index.html"
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk clockRate 0

set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 1
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 1
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitStates 1
set_interface_property s1 writeWaitTime 1

set_interface_property s1 ENABLED true

add_interface_port s1 chipselect chipselect Input 1
add_interface_port s1 address address Input 3
add_interface_port s1 write write Input 1
add_interface_port s1 writedata writedata Input 32
add_interface_port s1 read read Input 1
add_interface_port s1 readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point external
# | 
add_interface external conduit end

set_interface_property external ENABLED true

add_interface_port external cs export Output 1
add_interface_port external sclk export Output 1
add_interface_port external mosi export Output 1
add_interface_port external miso export Input 1
add_interface_port external cd export Input 1
add_interface_port external wp export Input 1
# | 
# +-----------------------------------
